language: ruby
rvm:
- 2.2.3
before_install:
- nvm install 4.2.3
- npm install
- npm install gulp-cli
- npm run build
install:
- bundle install
script: bundle exec middleman build
after_script:
- gem install percy-cli
- percy snapshot _site/
deploy:
  provider: npm
  email: scprdev@scpr.org
  on:
    tags: true
  api_key:
    secure: u6NrJ1+5eL4XjFpvYN5la8SOhUQ/KAutJNkzRCbiAtNGi8f0oCSSwozoRJxZowrTeXWCcbc9ZPqI0IXMLD0JFz4exF2tTZ60IDbEjU84ze4atxKcR5N0xS6sIFiYftAMzZ6on7pLZweFjaLCg/Yge9AAP/US12cF/5QAvpJQFI+EdhzMNntLKoWXaZzZZEglPu5OLYV9xQCeq6W5rDvq01jbkWwN4CfLp6o3+uMCQkZX/rm6XGBT/QdnCC/I9zKe5Ion4HswJ6rFJLlNscWa1K7p7uRxx3kR233qSB2mnyq7SXSOBffaJKAJt37/xBNrogCf6SE4pidjsLjpKgOeFEwPb1DmcFTW0p8bm6mPM+H5uoHG1UYpGj8Ayrz7KNy6KnCxNhBi4tGYhjqSV0Y07lbxVLwmW7n/d/EIWKvz4YCFpmnXzSIghwfcZjzuBYADc2eFZb8gudQlHERX14sGKZTGMrKWt7qmvs4/QJhdNlluPkXlpu/aEdrmDTc8Hz/FHuFelULdNIH6tl7uoBX4miotgsGJhizN66pvWogr7Kz6783QI6F5H+iTywEmU2VfEZS6pd8NVRogxF1FGt+SM3APs0C1xEaOwUhIO5UP952OT3R4r4KGy+h8XDpVJ/8zqAIcZFZN83LKv3W01s/Gppjat7ronne3EriEDZ/rxQw=
env:
  global:
    secure: NjAkBaViz8sUM0ChzQG5lR9ty7e6xYA3arFeQ3gVrlXwLMNJG6oN3dUKu2LjCHNIm4eTpM9EtR1ra+HwVt3BK7OGl+ebbHcROLPot1mCL8w8NW/bREW0KfZ1oq7wFdzSpinDZOS1ezfVMW+hah+rDVHNsiHoMq9wCNyThBiGGx55MOIkBmwJuJDBjuTTePmwOiRsFT6YWe5e3M5Z8xlzQjzaPN8PmxUv+kI8TXDUiFJ1018CZK7hUwQEXvcAQYlhvzPJ3FxnzIqdcF7UoGU8AFeqRZMy0DcWkNI5rMcWq0iqR0Jm5eUbB30S3WVko8wBYpwGKhQZl3lROzNj0eAwj0KwSeahDpfzJ+9SA5WDJDJ+IS0peed6n82DwuW39hVLf/aJo6SQEBY/QMklZ0LrDmq5AGl9vrSfE0nuxEs2TUyz9mkeTkrkMe6QhIe09NTrPBSN64gtg+oGl7Il1sut+xqJbBU2jvDMDmj+7nk3kA2ziX+LhWY/62ZQvljyntUIhKVhxkxBR55K09dSVZGZtx8OX/L3kWK527HUW5vYcb4fZhnmm1+v2aPpWr64me+RIUwddJLwDY0l+Ui22TwpcdO5TpnUKDLSOs4vRUuBpjRsu2WrEhwZPx2fxRLX4ZZhvQkSl5BlcXJ13lJjwVBc9jW2RouFdkQR3R0I1gePiW4=
notifications:
  slack:
    secure: XG/WNoMJucmkuFUPlPewwfndfCgSvp+ONHneuNaobsExecDbLkbR45ASHlnZjlTtgyjlJ7hm0VIBCe4SqpgmjxuUaOhq3uur07f1QDRw7jjVJykRxF0u8FW7BQux/05fxOKTOIfrQ0NkZ7LFJUsDDF5ZjF6hoGSDguvstDD07/Wdf2wgIk4l8u/BPK2I040dd8TjRhocSqc+euLtYRRmSe95yC95O72GoGJ7uY2ZvGDZX3wgHJVFitMIPbTEtNyMbCBUnkLQgwfKdEqQphIEc400Y1+01w8RbJ/lwtyKu+8f2sIswjs5X8RvOV3Kqd6xLyT3dFfl9e/V4Dj/6Zl6s91VySnPTe+Qo7DMMNoc7zxCQVrp5rcShju6EfYqfimsMRIbb5tR8cYfDEjwTVjwutcpIoDC+SFvSCRj/iODBh3lUYfXEEUyCIATz+1I4flQdcDAoyhbPJh/G/spWUnTtyzrpZrftnu1XUObxfrrgLCzjSMX0yDlyJj9xTI0BqBhUVF3IyZaXbQqorbPH1Yx3tWQdysHhNO3tZ7JtzIKU0q6YMrh0aG284Ja8hl0DkZSHJFsdOaVjNz4iQXtu9TuFVd/4kaLDOZwb1gvmDurhrp11uICS/oLMeO/tA3cXpi9QtzkR+KMmPsXKqcP0cWubrxqYW5xW1Dnfvq50foFqIc=
